service: mailing

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  mailing:
    handler: handler.handler

plugins:
#  - serverless-dynamodb-local
  - serverless-offline

#resources:
#  Resources:
#    usersTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: mailing
#        AttributeDefinitions:
#          - AttributeName: email
#            AttributeType: S
#        KeySchema:
#          - AttributeName: email
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1




